### ISSUE TITLE
Need to pin docker image to a Release Version of OpenEMR

### ISSUE THREAD

**Issue by TheToolbox** [openemr/openemr-devops#1]
For production use of the openemr docker image, we should be using an official release, ideally 5.0.0 (or latest). Currently, this causes an adodb incompatibility [issue](https://github.com/ADOdb/ADOdb/issues/257) with php7.1. Ideally, we could backport the adodb update, but some discussion of the optimal solution is warranted.

**Comment by jesdynf** [comment]
Safe to close?

**Comment by TheToolbox** [comment]
Fixed by #6. Now pinned to rel-500 (alpine 3.5, php7.0)
