### ISSUE TITLE
Automatic Setup

### ISSUE THREAD

**Issue by TheToolbox** [openemr/openemr-devops#10]
OpenEMR should set itself up on first run, so that the administrator doesn't need to run through setup.php manually. It seems currently that the best plan would be to use environment variables passed into the container to set the DB and credentials.

**Comment by bradymiller** [comment]
Agreed. Could even have an implicit option here. If don't get the necessary environmental variables or something goes wrong, then revert to manual setup.php. If get the necessary variables and things goes well, then go to autoinstall bliss.(same strategy is used for the ubuntu/debian/mint install package)

**Comment by TheToolbox** [comment]
Sounds very reasonable. Conveniently all that needs to be done to enable that is not to generate config.php (and of course not populate the db) if the env variables aren't set.

**Comment by bradymiller** [comment]
Not sure if I've pointed this out yet, but note there's a autoinstall script here (used by ubuntu packages and demos) that will do all the heavy lifting for you if go for autoinstall bliss:
https://github.com/openemr/openemr/blob/master/contrib/util/installScripts/InstallerAuto.php
(let me know if you need me to point to examples of use)

**Comment by jesdynf** [comment]
The MySQL docker script has an entrypoint that'll just instajam SQL into the server during the initial setup.

**Comment by TheToolbox** [comment]
Added feature at 000a206. Any problems with it/behavior adjustments should be tracked as new issues
