### ISSUE TITLE
Open Collective Text

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr-devops#111]
Saw this while running a container today (nodemon is a popular node-related package):

```
Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate
```

How do y'all feel about me `echo`ing this (`%s:/nodemon/OpenEMR`) in our `run_openemr.sh`?

**Comment by MatthewVita** [comment]
@bradymiller @jesdynf @TheToolbox

**Comment by bradymiller** [comment]
As long as it does not break anything, no issues here.

**Comment by jesdynf** [comment]
Seems reasonable.

-- 
Asher Densmore-Lynn <jesdynf@gmail.com>

**Comment by MatthewVita** [comment]
https://github.com/openemr/openemr-devops/pull/112
