### ISSUE TITLE
memory_limit of 128M may be too low

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#126]
@sjpadgett , @TheToolbox , @jesdynf 
Sounds like Administration->Backup in 5.0.1 docker is breaking because of memory issues. Still needs more testing to confirm this. If we do increase the memory_limit to 256, for example, will this cause further memory use problems by the docker (I recall that there was discussion of increased memory use and issues by 5.0.1 already).

**Comment by jesdynf** [comment]
It will, but we had already given up on nano anyways, right? Nano to micro gives us 512 megs more to play with; losing 256 isn't the end of the world.

**Comment by jesdynf** [comment]
Wait, are you saying MySQL needs more RAM, or the docker containers do? I can modify the docker if I need to add a config-file, but are you actually talking about the container?

**Comment by bradymiller** [comment]
It is the memory_limit setting in the php.ini config file (how much memory a php script is allowed to take up) that we bring in when we build the docker. So easy to adjust and rebuild dockers.

**Comment by jesdynf** [comment]
I've got a 5.0.1 compliance commit coming right now -- am home sick -- so I'll bump it to 256M and see what happens.

**Comment by bradymiller** [comment]
I just pushed a small commit after yours to increase flex to 256M also. When I get some time today, I'll build the dockers and test them (and push them if they test well).

**Comment by bradymiller** [comment]
dockers are pushed and the backup now works, so closing this issue
