### ISSUE TITLE
5.0.1 container fails to start with existing 5.0.0.5 Deployment and Domain variable set

### ISSUE THREAD

**Issue by daurrutia** [openemr/openemr-devops#127]
Express plus 5.0.0.5 deployment with "openemr/openemr:latest" image setting failed to start. 

Previously configured Domain variable set in docker-compose.yml

First reported today, may have began to occur earlier.

Docker-Compose logs show Certbot/LetsEncrypt challenge fails. 

Docker container fails to start.

Tag modification to "openemr/openemr:5.0.0" with docker-compose up was successful to start.

**Comment by jesdynf** [comment]
@daurrutia I don't know how much I'd recommend trying to upgrade containers like that -- sticking with the existing container and running the OpenEMR upgrade procedure may be a better play. We don't have a container-specific guide for that yet, but https://www.open-emr.org/wiki/index.php/Linux_Upgrade_5.0.0_to_5.0.1 covers the general procedure.

(Alternately, an Express Plus deployment that *starts* at 5.0.1 was just pushed live.) 

@toolbox Could we have introduced breaking changes, if somebody installed the older container and then tried to migrate to the newer one in place?

**Comment by TheToolbox** [comment]
If I recall, the letsencrypt code is (supposed to be) exactly the same in 5.0.0 and 5.0.1. Could we see a copy of the logs? Maybe there's somehow a networking difference between the containers.

**Comment by daurrutia** [comment]
Unable to reproduce the startup issue. 
Tag modification to 5.0.1 with docker-compose up was successful to start with SSL.

However, possible separate issue, received database error on logon (screenshot attached).
<img width="789" alt="20180426capture" src="https://user-images.githubusercontent.com/13512616/39342155-938101ee-49a4-11e8-8e89-580548d7a3ff.PNG">

Any ideas?

**Comment by jesdynf** [comment]
That one I know -- you need to run the 5.0.1 schema upgrade scripts if you're using the 5.0.1 container. https://github.com/openemr/openemr-devops/blob/master/packages/lightsail/upgrade.md for more information.

**Comment by daurrutia** [comment]
That makes sense. Thanks @jesdynf and @TheToolbox.
