### ISSUE TITLE
jonnalagaddda

### ISSUE THREAD

**Issue by jonnalagaddda** [openemr/openemr-devops#134]
Hi Brady,
can please tell me the how to run the openemr/openemr on port no 8080,were i want to change the port no?i am the new person on docker containerzation.please help me.

**Comment by TheToolbox** [comment]
Hello and welcome @jonnalagaddda! These issues pages are a bit ill-suited to installation questions (they're intended more for bug reporting and feature requests). Our chat (chat.open-emr.org) is a much better place to answer your question and we'd love to help you there!
