### ISSUE TITLE
jonnalagaddda

### ISSUE THREAD

**Issue by jonnalagaddda** [openemr/openemr-devops#136]
Hi Brady,
    i am not able to run the openemr on port 80:80,when i will run the command like # docker run -it --name my_openemr_container -p 80:80 openemr/openemr i am getting issue like >>>

Generating a 4096 bit RSA private key
..........................................................................................................................................................................................................................................++
........................................................++
writing new private key to '/etc/ssl/private/selfsigned.key.pem'
-----

Love OpenEMR? You can now support the project via the open collective:
 > https://opencollective.com/openemr/donate

Starting cron daemon!
crond[14]: crond 4.5 dillon's cron daemon, started with loglevel notice
Starting apache!
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message

thanks in advance.

**Comment by jesdynf** [comment]
As previously explained, questions of this nature are best answered in our forums. Thanks.
