### ISSUE TITLE
openemr/openemr

### ISSUE THREAD

**Issue by jonnalagaddda** [openemr/openemr-devops#137]
Hi Brady,
 this is jonnalagaddda, i am getting issue like 
OpenEMR Setup

Step 3

Configuring OpenEMR...

Connecting to MySQL Server... ERROR. Check your login credentials. unable to connect to database as root ,i was tried but i am not able connect the server please reply me as soon as possible
thanks advance,
nagendra.

**Comment by robertdown** [comment]
Hi @jonnalagaddda, I recommend posting this to https://community.open-emr.org for support. Initially though, it seems your root password is incorrect
