### ISSUE TITLE
Choosing db side of db.t2.micro causes stack installation to fail.

### ISSUE THREAD

**Issue by JXPrime** [openemr/openemr-devops#142]
Trying to install the Standard sku will fail if you choose db.t2.micro, I got the following error:

DB Instance class db.t2.micro does not support encryption at rest (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 9a9374b8-fbd5-4fdc-9295-754e78b74c71)

Can that be filtered from the list in the template somehow?

**Comment by jesdynf** [comment]
Well, fancy that. Yeah, I'll yank it from the next revision. Not sure how I missed it, though -- are you in us-east-1?

**Comment by JXPrime** [comment]
That was the region I was testing with, yes. Thanks! After poking around I saw it in the template I probably could have just submitted a PR for it. :D

**Comment by jesdynf** [comment]
It's in now, but it'll take a little while for Marketplace to catch up. Thanks a ton!
