### ISSUE TITLE
docker build for 5.0.2 is failing

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#158]
Getting the following error during 5.0.2 docker build:
```
Cloning into '/opt/certbot'...
Obtaining file:///opt/certbot/acme
Obtaining file:///opt/certbot
Collecting cryptography>=0.8 (from acme==0.29.0.dev0)
  Downloading https://files.pythonhosted.org/packages/d2/5f/6ed3135eb1e775187f7ecd4e7713f1415516725365e51f9786143f36e024/cryptography-2.4.1.tar.gz (468kB)
  Could not find a version that satisfies the requirement cffi!=1.11.3,>=1.7 (from versions: )
No matching distribution found for cffi!=1.11.3,>=1.7
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c apk add --no-cache git build-base libffi-dev python-dev     && git clone https://github.com/openemr/openemr.git --depth 1     && rm -rf openemr/.git     && cd openemr     && composer install     && npm install --unsafe-perm     && npm run build     && composer global require phing/phing     && /root/.composer/vendor/bin/phing vendor-clean     && /root/.composer/vendor/bin/phing assets-clean     && composer global remove phing/phing     && composer dump-autoload -o     && composer clearcache     && npm cache clear --force     && rm -fr node_modules     && cd ../     && chmod 666 openemr/sites/default/sqlconf.php     && chmod 666 openemr/interface/modules/zend_modules/config/application.config.php     && chown -R apache openemr/     && mv openemr /var/www/localhost/htdocs/     && git clone https://github.com/letsencrypt/letsencrypt /opt/certbot     && pip install -e /opt/certbot/acme -e /opt/certbot     && mkdir -p /etc/ssl/certs /etc/ssl/private     && apk del --no-cache git build-base libffi-dev python-dev' returned a non-zero code: 1
```

This appears to be pinpointed to following in the DockerFile:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/5.0.2/Dockerfile#L39

**Comment by TheToolbox** [comment]
Looks like an issue in building certbot. I'll see if I can find some time in the next few days to poke at that process and improve robustness. Pip is 8(!) versions behind in that container too, which might have something to do with it not finding a candidate package.

**Comment by danehrlich1** [comment]
@TheToolbox I almost had a heart attack reading Pip was 8 versions behind but it looks like they skipped from version 10 directly version 18. I only know this because Oracle did something similar for their database, version 12 to version 18 (what is it about 18?)

Back on topic, I had some luck changing Alpine Linux to 3.8.1 (from 3.8.0) but it still failed just farther down the build process...

**Comment by bradymiller** [comment]
hi @TheToolbox ,

Just made an issue to work on the fix:
https://github.com/openemr/openemr-devops/issues/159

-brady

**Comment by bradymiller** [comment]
hi @TheToolbox , Just checking if there's been any progress to fix the certbot issue that is breaking the build?

**Comment by danehrlich1** [comment]
This currently is working fine? I had no problems running a thousand tests on the Docker container last two days while building my other firewall docker container.

To confirm, the command I'm running is: `sudo docker run openemr/openemr:5.0.2`
