### ISSUE TITLE
multisite setup guide

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr-devops#160]
hi @jesdynf , thanks again for all of the work that went into this which allows me to use it in production

trying to set up multi site but it looks like I'll need to retrieve setup.php kind've like you outline in the upgrade.md script

also will need to connect to mysql to create a new database so will have to allow mysql into the ec2 instance and docker

will do my best to hack this but will probably need your guidance

**Comment by stephenwaite** [comment]
cool, first step (assuming have access to mysql docker to create a new database)
* you pull in setup.php and change these values to true, https://github.com/openemr/openemr/blob/rel-501/setup.php#L25-L36

**Comment by jesdynf** [comment]
Instead of changing a file, which is awful and annoying to automate, why
not have a setup-multisite.php file somewhere outside the execution root,
and copy it in when it's needed and delete it after?

**Comment by stephenwaite** [comment]
yup, sounds wise but Brady set it up that way :)
after hacking my solution am able to log in but am redirected to default site instead of new site
so login url which is only altered by ?site=new site name isn't sticking after login

**Comment by jesdynf** [comment]
I can't think what would cause that. You may need to check the Apache logs
on the container to see if something non-obvious is happening and you're
being redirected somehow?
