### ISSUE TITLE
Automated Recovery Error: sed: sqlconf.php: No such file or directory

### ISSUE THREAD

**Issue by daurrutia** [openemr/openemr-devops#167]
https://github.com/openemr/openemr-devops/blob/149f88bd21391d86223e3e94c0171e8102361cc6/packages/standard/ami/ami-configure.sh#L48

Automated recovery error encountered during instance provisioning for Standard package.

From openemr-configure.log:
```
+ sed -i 's/^\$host\t=.*\;$/$host\t= '\''ordxhkay021241.crjizceofxav.us-east-1.rds.amazonaws.com'\''\;/' /mnt/docker/volumes/standard_sitevolume/_data/sqlconf.php
sed: can't read /mnt/docker/volumes/standard_sitevolume/_data/sqlconf.php: No such file or directory
```

Verified sqlconf.php is not in _data/. 

Anyone else come across this?

**Comment by jesdynf** [comment]
Is it transient? Does it happen every time?

What *is* in that volume, out of curiositiy?

**Comment by daurrutia** [comment]
I think I may have found the issue. 
Line 48 above is missing the full path. Should read:
`sed -i "s/^\\\$host\t=.*\;$/\$host\t= '$RECOVERY_NEWRDS'\;/" /mnt/docker/volumes/standard_sitevolume/_data/default/sqlconf.php`
Which includes the `default `directory.

It does happen every time on the handful of times I've tried it.
The `default `directory is in the recovery instance's volume under `_data/`.

**Comment by daurrutia** [comment]
Yep, tested AMI on my end. The path is incomplete.

**Comment by jesdynf** [comment]
You've correctly identified the source of this problem, I cannot deny it, but if this was broken as you surmise then Standard should never have worked for anybody, ever, including during my testing. Currently thinking.

**Comment by jesdynf** [comment]
Ugh, here it is. How this lasted for so long without correction, I cannot guess, but the change that broke this happened in https://github.com/openemr/openemr-devops/commit/02c23ac102e839e2c623efa5154fba1bdf510bd0 .

**Comment by jesdynf** [comment]
If you'll file this as a PR on my branch, I'll accept it (to properly credit you) and then rebuild a new image and submit it to Amazon. Turn-around on that process may be a few days, though. Sorry to put you to this trouble!

**Comment by daurrutia** [comment]
No apologies needed here, thanks for your work.

Which branch specifically?

**Comment by daurrutia** [comment]
Just a friendly reminder @jesdynf .. the AMI and it's CFN mappings will need to be updated. Are we 1 man deep with that process?

**Comment by jesdynf** [comment]
I'm really sorry it's taken this long to attend to this -- every time I try to touch it, something's in the way. I'll at least delete several obstacles before the end of this evening; I'll let you know here when it's cleared.

**Comment by jesdynf** [comment]
Alright, 5.0.1-6b has been submitted to Amazon. It may take them a while to process the request, though.

**Comment by jesdynf** [comment]
Okay, it's up! I'm sorry it took this long to get taken care of, but 5.0.1-6b is in the Marketplace and I've verified it functions. I'm going to close this, but reopen it if it's still broken. Thanks!
