### ISSUE TITLE
Unable to launch full_stack

### ISSUE THREAD

**Issue by daurrutia** [openemr/openemr-devops#170]
Attempting to launch into us-east-1 from:
https://github.com/openemr/openemr-devops/blob/master/packages/full_stack/chapters/01-Getting-Started.md

Receiving S3 access denied at CloudFormation console for:
https://s3.amazonaws.com/openemr-cfn-useast1/OpenEMR.json

Is it just me?

**Comment by jesdynf** [comment]
Try again?

**Comment by daurrutia** [comment]
Yup, got past that. Thanks.

**Comment by dummys** [comment]
hi, same error here: Unable to download from S3 location (Bucket: openemr-cfn-uswest2 Key: openemr.zip). Reason: Forbidden (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: e77ea5ad-8c3c-4d15-8eea-f96aa4e51df4)

**Comment by dummys** [comment]
I tested manually and you fail to set the correct right (read-only)
