### ISSUE TITLE
Add section on GeoIP blocking to Full Stack - First Timers

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr-devops#172]
There should be an "Optional" section at the end of Secure Domain Setup allowing a user to configure GeoIP blocking for their domain.

Users in the US should be very encouraged to take this option, although users in Europe (many small countries close together) might want to be more careful.

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-geo

This issue is very easy and be will first-timer-only kind of stuff.

**Comment by danehrlich1** [comment]
Lol yes I am obsessed with GeoIP blocking but it is so easy! And most security guides want it now along with 16+ passwords :)

**Comment by jd-santos** [comment]
Did some poking around and didn't find much about implementing this on Route53, but a lot of references for doing it in CloudFront. Here's a [Stackoverflow question](https://stackoverflow.com/questions/35080803/restricting-website-access-by-country) where a user suggests implementing at the application level.

**Comment by danehrlich1** [comment]
1. @bradymiller Looks like this will need to be done at the app level per this [issue](https://github.com/openemr/openemr/issues/2098). I will implement it myself in a few weeks.

2. @jd-santos This can also be done in AWS via the App Load Balancer + WAF route. I like this strategy as well as the code-level one above, but this increases cost by $35~/month, which can be very tough for 3rd World. 

3. @jd-santos Going to create another issue for you to research App Load Balancer + WAF route. I will make sure the issue is very well documented IN ADVANCE so that it should be pretty easy for you. This solution will be only for our US based users (which is quite a few) who can afford the uplift in price.
