### ISSUE TITLE
Random Other MySQL Security Things

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr-devops#179]
Not sure if possible but should be investigated:
- Run as normal user: https://dev.mysql.com/doc/refman/5.7/en/changing-mysql-user.html
- Connection control plugin: https://dev.mysql.com/doc/mysql-secure-deployment-guide/5.7/en/secure-deployment-connection-control.html
- Look into LOAD DATA concerns: https://dev.mysql.com/doc/refman/5.7/en/load-data-local.html
- Whatever this is? https://dev.mysql.com/doc/mysql-secure-deployment-guide/5.7/en/secure-deployment-post-install.html#secure-deployment-mysql-files
***
- This? https://www.owasp.org/index.php/OWASP_Backend_Security_Project_MySQL_Hardening
- Handy CIS Benchmark document: https://drive.google.com/file/d/1M2YofVXaRN_QGbH9nkaF8pDXkanIrujx/view?usp=sharing

OTHER RANDOM POTENTIALLY HELPFUL INFO:

- Do not permit the use of symlinks to tables. (This capability can be disabled with the --skip-symbolic-links option.) This is especially important if you run mysqld as root, because anyone that has write access to the server's data directory then could delete any file in the system! See Section 8.12.3.2, “Using Symbolic Links for MyISAM Tables on Unix”.

- Control FILE privilege

- To limit the location in which files can be read and written, set the secure_file_priv system to a specific directory. See Section 5.1.7, “Server System Variables”.

**Comment by joshuaaguilar20** [comment]
I Will take this issue going to start working on it now

**Comment by joshuaaguilar20** [comment]
@danehrlich1  @bradymiller 

** Connection control plugin:**
Got the fix for this. I was wondering if you guys wanted to use the default values for the plugin or there were custom global values you wanted to set? 


Default Values with Connection Plugin 
- connection_control_failed_connections_threshold = 3 
connection_control_max_connection_delay = 2147483647 
connection_control_min_connection_delay = 1000

**Comment by danehrlich1** [comment]
https://dev.mysql.com/doc/mysql-security-excerpt/8.0/en/connection-control-installation.html

Try this for now. After the 5th failed attempt, we'll add 3 seconds of delay all the way until 100 seconds of delay, then we drop them:
```
connection_control_failed_connections_threshold = 5
connection_control_max_connection_delay = 100000
connection_control_min_connection_delay = 3000
```

**Comment by bradymiller** [comment]
hi @danehrlich1 and @joshuaaguilar20 ,
Are these changes/settings that will go into docker-compose, like how the `-character-set-server=` setting is done:
https://gist.github.com/bradymiller/8f8dc5215b07d287f7dc0fed80bf2b9d/#file-openemr-502-docker-example-docker-compose-yml-L11

**Comment by joshuaaguilar20** [comment]
@bradymiller  @danehrlich1  Brady The above suggestion will not work, as the plugin is not installed by default :/.  The changes actually must be made inside of the docker container (image my.cnf file) ' or installed at Run-time, **but must start the plugins at startup and** prevent them from being removed at runtime.
 
I was able to start the container  and CD into the Root DB image  ** my.cnf folder **. 

 ** Here is the current server config. currently ** . 
https://gist.github.com/joshuaaguilar20/a45cb36e40c4dae754de04bf5ae75238


The fix would be to add the below to the my.cnf file and then make the changes to start it in the YML file. 




![plug](https://user-images.githubusercontent.com/31646651/53055416-753bce00-345c-11e9-9f3f-fc04fc8a36d7.png)


The interesting question is when we make the updates to the my.cnf image how do we make it stick to the container? Creating a new image, or adding some sort of volume folder with the new settings in the YML file. Alternatively if you want to do it on run time, I found the code for that as well. I figured you guys could check the cnf file and see if it needs any security changes? Hope this helps. 

![load](https://user-images.githubusercontent.com/31646651/53055794-ed56c380-345d-11e9-8cba-ee6735fbe7b8.png)


docs
plugin load - https://dev.mysql.com/doc/refman/8.0/en/plugin-loading.html
mariadb plugins- https://mariadb.com/kb/en/library/mysql_plugin/

**Comment by danehrlich1** [comment]
Joshua:

1. It looks like we are going to create a separate config file and just copy and paste it into the container? This is actually quite easy, we are already do it with `openemr.conf` and `php.ini` [here](https://github.com/openemr/openemr-devops/tree/master/docker/openemr/5.0.2).

2. NOTE: Let's move this issue over to our "Secure Docker Repo" [here at this link](https://github.com/openemr/docker-madness/issues/16). This repo is where I am fine tuning a very very secure OpenEMR Docker Container. It also is a testing ground for merging things back here. Some of the cool stuff:
- based on secure Google Debian image
- ModSecurity WAF Firewall
- GeoIP Country Blocking
- Mod_Evasive apache block
- Secure NTP
- DNSCrypt

3. Good work here. This will help here, for OWASP, and even with some stuff I have to do my day job. Not bad for a single Github issue!
