### ISSUE TITLE
How can I see the code inside the VM.

### ISSUE THREAD

**Issue by MadibaLab** [openemr/openemr-devops#183]
How can I see the code inside the VM. I installed from the appliance ( the latest option).

**Comment by boxlady** [comment]
If you are using a local docker and you want to get into the container then you can do this:
`docker exec -it <container-id> bin/bash ` will get you inside the container. you can then navigate to the folder which I believe is /var/www/localhost/htdocs/openemr. If that wasn't you question then can you be more specific?
