### ISSUE TITLE
Docker Image Patch Level

### ISSUE THREAD

**Issue by daurrutia** [openemr/openemr-devops#184]
Docker image 5.0.1 is at patch level 1 is that correct?

Any way to update it to patch level 6?

**Comment by bradymiller** [comment]
hi @daurrutia ,
It is updated to patch 6 (Go to the About link in the top menu and is should show 5.0.1(6)). There is also a patch 7 that is currently available (I didn't rebuild the 5.0.1 docker with this out of concerns of docker building bugs(not any problems with the patch 5-0-1-Patch-7.zip); see here on how to update to patch (would be 7) in docker here:
https://github.com/openemr/openemr-devops/tree/master/packages/lightsail#applying-upgrades-and-security-patches

**Comment by daurrutia** [comment]
Thanks. Any current plans to upgrade the docker image to 5.0.1(7)?
