### ISSUE TITLE
portal (and likely api) sessions not working in docker

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#188]
hi @danehrlich1 ,

This change is breaking the sessions created in the patient portal (code in portal directory) and I bet will also break session stuff for api/fhir stuff:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/5.0.2/php.ini#L1396

Any thoughts on either reverting it back to `/` or another setting.

(fyi, @sjpadgett , this is the session issue I was working on)

thanks, -brady

**Comment by sjpadgett** [comment]
You shouldn't set absolute path for cookies for several reasons but mainly we set to document root to prevent site from different domains sharing sessions. This addressed a security flaw re matrix a couple years back. Should be a thread on forum which covers. Look at restoresession and login to see how it is done

**Comment by bradymiller** [comment]
hi, So we should be good to just revert it back to default setting of `/` then. Will wait for input from @danehrlich1 before I fix this in the dockers.

**Comment by sjpadgett** [comment]
I would think we reset the path anyway on login. I think the problem is localhost in path. Maybe if set to domain or relative you'd be okay.

**Comment by danehrlich1** [comment]
Brady:

Delete that line. I’m working with Apache and PHP ppl to understand wtf it does, because it’s never consistent.

Maybe we can add it back in in 3 months, but not sure.

**Comment by bradymiller** [comment]
reverted it back to default setting and updated dockers
