### ISSUE TITLE
Migrate directory structure from 5.0.1 to 5.0.2 docker upgrade

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#190]
During upgrade from 5.0.1 to 5.0.2, will need to make following directory changes for each sites/* directory:
edi,era,letter_templates(migrate custom_pdf.php to base site dir), procedure_results to inside documents

Upgrade docs are here:
https://github.com/openemr/openemr-devops/blob/master/packages/lightsail/upgrade.md

**Comment by danehrlich1** [comment]
Is this something we should write a script for? Like a patch?

**Comment by bradymiller** [comment]
Hi,
It would be nice to have flags on the docker, so know when need to do docker specific upgrade stuff. For example, maybe a text file with the version number in docker `/root/` directory. Then when start the docker, would have 1 of 3 things happen during docker start up:
* If there no text file with the version number in `/var/www/localhost/htdocs/openemr/sites/` directory then do the docker specific upgrade stuff (move folders and the permission changes) and copy the text file with the version number from `/root/` to `/var/www/localhost/htdocs/openemr/sites/`
*If there is a text file with the version number in `/var/www/localhost/htdocs/openemr/sites/` directory then compare it to the text file with the version number in `/root/`. If they are the same, then do nothing. 
*If there is a text file with the version number in `/var/www/localhost/htdocs/openemr/sites/` directory then compare it to the text file with the version number in `/root/`. If `root` version is higher, then do the docker specific upgrade stuff (move folders and the permission changes) and copy the text file with the version number from `/root/` to `/var/www/localhost/htdocs/openemr/sites/`

**Comment by bradymiller** [comment]
@jesdynf and @TheToolbox ,
Can you think of a better way to do above?

**Comment by danehrlich1** [comment]
@bradymiller For the file you were going to put in root, just use `ARGS` instead during `docker build`?

**Comment by jesdynf** [comment]
I've given this some thought, and it sounds like it's a process that should be part of the script that runs when the docker cranks up. The docker script ("run_openemr.sh" I think?) should know that it happens to be "10" (pick an integer, please), and as part of the container startup, checks to make sure that the Docker filesystem believes it too is 10, by checking some status file.

Should it instead be 8, or 9, or something other than 10, then it runs fsupgrade-8.sh, which should upgrade the filesystem to be 9, and it keeps repeating this process until either an upgrade script fails or it's at version 10 and can proceed with container launch.

Seem reasonable?

**Comment by bradymiller** [comment]
Completed this here:
https://github.com/openemr/openemr-devops/pull/200

Now can do complete upgrade (both codebase and database) by simply updating docker image in docker-compose.yml (5.0.1 to 5.0.2) as long as the sites/ directory is a shared volume (and not sharing the entire openemr codebase on a shared volume for obvious reasons).

Also straightforward to support version upgrades in the future:
https://www.open-emr.org/wiki/index.php/Steps_for_an_official_release#7._Prepare_for_docker_upgrade

**Comment by bradymiller** [comment]
New upgrade doc is here:
https://github.com/openemr/openemr-devops/pull/201
