### ISSUE TITLE
Docker OpenEMR Base Build

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr-devops#194]
1. If we strip out the parts of OpenEMR that are unlikely to change as frequently, like `apk add ...` and a few other lines, these commands can be placed in a `base image` that is only built every now and then.

2. Future builds are much faster, reducing build cost and developer toil.

3. Kaniko is also a good tool for reducing build times: https://github.com/GoogleContainerTools/kaniko

**Comment by danehrlich1** [comment]
It's getting confused between the triggers set up over here on Github and the ones we have in GCP...let me troubleshoot

**Comment by bradymiller** [comment]
Is the branch (with above commits) on the main openemr-devops repo or your openemr-devops repo?

**Comment by danehrlich1** [comment]
it's on a feature branch
`feature/gh-194`

**Comment by danehrlich1** [comment]
In GCP I can tell the Build Trigger to look for my `cloudbuild.yaml` file. I am guessing this trigger only looks for such files at the top directory level? Also I turned off builds unless someone is doing a pull request for now. You can always test by building locally via: https://cloud.google.com/cloud-build/docs/build-debug-locally

Good for working out the syntax of `cloudbuild.yaml`

**Comment by bradymiller** [comment]
That branch looks like it is on the main openemr-devops repo. Should have branches from your github repo, that you then do a pull request from.

**Comment by danehrlich1** [comment]
@bradymiller Have got it here. Just added in / messing around with some new tooling: https://github.com/danehrlich1/openemr-devops/tree/feature/gh-194

Apparently we can set up a Docker Build Cache, same as you have on your local machine, in a GCS bucket (or S3 if we were on AWS not a Google specific thing). Should further cut the build times down.

**Comment by bradymiller** [comment]
Rec submitting a PR for your branch so we can see what happens during PR submissions.
