### ISSUE TITLE
Alpine 3.9 Image

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr-devops#196]
Thoughts on switch the base image to Alpine 3.9 with HTTPD from the Apache folks? https://github.com/docker-library/httpd/blob/75e85910d1d9954ea0709960c61517376fc9b254/2.4/alpine/Dockerfile

All the questions that we might have had about Apache seem to be taken care of in their install scrip. Also makes our Dockerfile quite a bit shorter.

Thoughts?

**Comment by jesdynf** [comment]
I'm not opposed in principle, but you'd want to do a lot of testing to make sure autoconfig.sh (which is the real heart of the OpenEMR config) works down all the branches.  You might find it easier to just take the lessons that config teaches us about the apache.conf file and port them over directly.
