### ISSUE TITLE
mysql user in packages with dockers

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#198]
We should use openemr/openemr for the mysql user/pass rather than root/root for the 5.0.2 release:
https://github.com/openemr/openemr-devops/blob/master/packages/lightsail/docker-compose.prod.yml#L24-L25

@jesdynf , this should likely work with no issues.

**Comment by jesdynf** [comment]
I think that should be fine if https://github.com/openemr/openemr-devops/blob/master/docker/mysql-xtrabackup/innobackupex.cnf is updated to match. Please make sure the openemr user has full privs to the database, though.

**Comment by bradymiller** [comment]
Don't worry, the mysql users gets full privs, which are set here during auto install:
https://github.com/openemr/openemr/blob/master/library/classes/Installer.class.php#L238
