### ISSUE TITLE
AWS Standard: OpenEMR 5.0.1(7) -> upgraded to 5.0.2: Cloud Trail Encryption Not Enabled

### ISSUE THREAD

**Issue by ralflukner** [openemr/openemr-devops#205]
**Situation**
I am starting to look closer at the AWS OpenEMR Standard’s Security by running built-in AWS security checks. I plan to post a few issues to provide information where AWS’s security checks recommend improvements for enhanced security. I realize that this is a very broad and complex topic … one on which I am still learning a lot. Hopefully, I can contribute a few things to improve the security of this system in the process for everyone who uses the AWS OpenEMR hosted versions.
Here is a simple issue to start with:

AWS Subscription Security Issues
#cloud-trail-encryption-enabled
Rule details
Edit
Description
Checks whether AWS CloudTrail is configured to use the server side encryption (SSE) AWS Key Management Service (AWS KMS) customer master key (CMK) encryption. The rule is compliant if the KmsKeyId is defined.
Config rule ARN

Trigger type
Periodic: 24 hours
Scope of changes
Resource types
Last successful invocation
August 25, 2019 11:17 PM
Last successful evaluation
August 25, 2019 11:17 PM
More Information:
S3 Bucket Name
openemr-36a3d……
**OpenEMR Version**
I’m using OpenEMR version 5.0.2 (install was originally 5.0.1x and then upgraded to patch 7)
**Browser**: Not relevant to this.
**Operating System**
I’m using: AWS Ubuntu
**Description:**
**Ubuntu 16.04.6 LTS**
Release:
16.04
Codename:
xenial
**Logs**: Not relevant to this issue.

**Comment by jesdynf** [comment]
Sorry this has taken so long! I've located the required statements to turn that on, but it's going to require a bit of testing. Any interaction with KMS can often be... fraught.
