### ISSUE TITLE
off instance express plus backup

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr-devops#206]
hi @jesdynf , was telling @bradymiller about this event today

`[01:30 PM PDT] At 4:33 AM PDT one of ten data centers in one of the six Availability Zones in the US-EAST-1 Region saw a failure of utility power. Our backup generators came online immediately but began failing at around 6:00 AM PDT. This impacted 7.5% of EC2 instances and EBS volumes in the Availability Zone. Power was fully restored to the impacted data center at 7:45 AM PDT. By 10:45 AM PDT, all but 1% of instances had been recovered, and by 12:30 PM PDT only 0.5% of instances remained impaired. Since the beginning of the impact, we have been working to recover the remaining instances and volumes. A small number of remaining instances and volumes are hosted on hardware which was adversely affected by the loss of power. We continue to work to recover all affected instances and volumes and will be communicating to the remaining impacted customers via the Personal Health Dashboard. For immediate recovery, we recommend replacing any remaining affected instances or volumes if possible. `

luckily my instance was recovered and had a fairly recent backup just in case had to personally restore OpenEMR for an account but do you have any advice on how to get the backups off of a single instance in order to prevent sad times :)

thank you

**Comment by jesdynf** [comment]
https://github.com/openemr/openemr-devops/tree/master/packages/express_plus#backups talks about the recovery options. Backups are pushed to S3 daily, and you can test it with the recovery CFN template.

If you had to fish individual files out of a damaged instance you'd do so by mounting the volume on a fresh instance, but that'd only be necessary for documents or records newer than the last backup, and (in the case of the database) would be non-trivial. No worse than any other post-disaster forensic work, but non-trivial.

**Comment by stephenwaite** [comment]
oh yeah, nice, thank you @jesdynf 
the instance just failed the reachability check again
how can I tell which S3 bucket belongs to this instance?

**Comment by jesdynf** [comment]
Check CloudFormation. Express Plus opened a stack and the outputs will tell you what to punch into the recovery stack.
