### ISSUE TITLE
apache writable sites/documents directory and subdirectories for 5.0.2 upgrade

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr-devops#207]
ran a flawless upgrade but had to issue commands like
`chmod u+w sites/800/documents/smarty/main`
and
`chmod -R u+w sites/800/documents/edi/history/`
in openemr docker

**Comment by jesdynf** [comment]
Wait, "/sites/800"? Are you running multisite?

**Comment by stephenwaite** [comment]
hi @jesdynf , yes

**Comment by jesdynf** [comment]
I don't have any experience with multisite or the upgrade process. Can you tell me where to look in the mechanisms (and give me a an idea of what the right code would be?)

**Comment by jesdynf** [comment]
Is this still relevant for 6.1.0 now that upgrades are automated?

**Comment by stephenwaite** [comment]
not sure, will create a new issue if come across it again
