### ISSUE TITLE
Stdout Logging

### ISSUE THREAD

**Issue by generalconsensus** [openemr/openemr-devops#209]
AC: In order to be able to send stdout logging to docker and ultimately k8s we need the ability to modify the logging location from logs to allow stdout/stderr logging which most k8s logging telemetry provides.

Note: Example of issue: https://github.com/openemr/openemr-devops/blob/21e941eb606368aa47392e6d48aaba4c1a0cad08/docker/openemr/flex-3.10/openemr.conf#L20

**Comment by jesdynf** [comment]
True but non-trivial. You'll need to either supply parallel openemr.conf files or template one and inject relevant commands in, and provide the argument to do so or otherwise as a docker-compose environmental variable and pick it up during the first-run stanzas of the launch.

**Comment by jesdynf** [comment]
Hey, quick question. I just spotted this in passing, while working with Kubernetes stuff myself. Does this seem like what you're after? https://serverfault.com/questions/711168/writing-apache2-logs-to-stdout-stderr

**Comment by jesdynf** [comment]
https://serverfault.com/questions/599103/make-a-docker-application-write-to-stdout or modifying the new `rotatelogs` pipes to tee them to /dev/stdout and /dev/stderr are probably your best bet. I don't want to do so generally, however, nor do I want to build a script toggle able to cope with this, so for now notes on how to extend your own containers will have to suffice.
