### ISSUE TITLE
`rm auto_configure.php` causes crash after auto-config

### ISSUE THREAD

**Issue by TheToolbox** [openemr/openemr-devops#21]
Looks like by adding the second `rm auto_configure.php` [here](https://github.com/openemr/openemr-devops/blob/c6abcdab46eab77bcd1c53fa7aed2a186a07f857/docker-images/openemr/run_openemr.sh#L83), it's trying to remove the file twice. Removing it the first time seems likely to be sufficient, although I have to test the behavior of stopping and restarting a container to better understand which things will be persisted. Additionally, we may need to take some steps to properly persist the permissions that are done during autoconfig. Presently, they may be lost when a container is killed, but its site volume is preserved, and a new container is started in its place. The logical solution seems to be to move them into a separate 'if' block, checking only if `$CONFIG == 1` and then re-applying the permissions forcefully. That would honestly take care of both issues I think.

**Comment by bradymiller** [comment]
doh, sorry about that. Was making sure it got remove, if user did a manual configuration.
Can we just remove it if it exists?

**Comment by jesdynf** [comment]
rm -f

**Comment by bradymiller** [comment]
``````
if [ -f $FILE ]; then
``````

**Comment by bradymiller** [comment]
even better on the -f flag

**Comment by jesdynf** [comment]
No, if it's an rm, `rm -f $FILE` is safe, it won't crash or return non-zero if the file doesn't exist.

**Comment by bradymiller** [comment]
agreed
go with the rm -f ...
