### ISSUE TITLE
question, why using apache and not Nginx + php-fpm ?

### ISSUE THREAD

**Issue by dummys** [openemr/openemr-devops#215]
Is it a design reason ? Nginx+php-fpm are more fast than apache. We are suffering from slowness using the full stack and we are wondering where the culprit could be. Do you have an idea ?

**Comment by bradymiller** [comment]
hi @dummys ,

Guessing @jesdynf will weigh in on some of your other issues soon. OpenEMR can work with nginx/php-fpm although is considered experimental:
https://www.open-emr.org/wiki/index.php/OpenEMR_with_nginx_and_php-fpm

I actually use it in the development stack I use to allow testing of the more recent php versions:
https://github.com/openemr/openemr/tree/master/contrib/util/docker#insane-development-docker-environment

Got an active issue for nginx related things here:
https://github.com/openemr/openemr/issues/1696

-brady

**Comment by dummys** [comment]
hey @bradymiller ok cool. What did you think of my other issue ? did you have the same problem with /openemr ? For me it's annoying because then I need to use elburl/openemr, why not pointing the elb stack to /openemr directly ?
