### ISSUE TITLE
Add PHP Developer tools to docker environment

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr-devops#228]
### Description
Hello @bradymiller, This is in reference to the issue discussed [here](https://github.com/openemr/openemr/issues/3193). I was thinking a good starting point would be creating an issue to bring in the developer dependencies here. 

### Describe the solution you'd like
Add support to the development docker to allow the developer to do the following in the docker:

php syntax checking (DONE)
psr2 checking/fixing (DONE)
unit tests (DONE)
e2e tests (DONE)
api tests (DONE)

Once you confirm this is the way to go, I would add the scripts as you described in the issue above

**Comment by bradymiller** [comment]
sounds great!

**Comment by bradymiller** [comment]
See bottom posts of https://github.com/openemr/openemr-devops/pull/230 for why re-opened this.

**Comment by bradymiller** [comment]
ok, the docker is now updated and live :)
Here is the command to create a report of PSR2 issues:
```
docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cd openemr; php -d memory_limit=512M /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcs -n --extensions=php,inc --standard=ci/phpcs.xml --report=full .'
```

And here is the command to fix the PSR2 issues:
```
docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cd openemr; php -d memory_limit=512M /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcbf -n --extensions=php,inc --standard=ci/phpcs.xml .'
```

Interestingly, here is the output I get now with both commands:
```
[00:54][brady2@brady2-gaz:/var/www/openemr]$ docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cd openemr; php -d memory_limit=512M /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcs -n --extensions=php,inc --standard=ci/phpcs.xml --report=full .'

FILE: /var/www/localhost/htdocs/openemr/sites/default/sqlconf.php
----------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 6 LINES
----------------------------------------------------------------------
  5 | ERROR | [x] Spaces must be used for alignment; tabs are not
    |       |     allowed
  6 | ERROR | [x] Spaces must be used for alignment; tabs are not
    |       |     allowed
  7 | ERROR | [x] Spaces must be used for alignment; tabs are not
    |       |     allowed
  8 | ERROR | [x] Spaces must be used for alignment; tabs are not
    |       |     allowed
  9 | ERROR | [x] Spaces must be used for alignment; tabs are not
    |       |     allowed
 31 | ERROR | [x] A closing tag is not permitted at the end of a PHP
    |       |     file
----------------------------------------------------------------------
PHPCBF CAN FIX THE 6 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 1 mins, 52.06 secs; Memory: 505.01MB

[00:58][brady2@brady2-gaz:/var/www/openemr]$ docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cd openemr; php -d memory_limit=512M /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcbf -n --extensions=php,inc --standard=ci/phpcs.xml .'

PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
...ocalhost/htdocs/openemr/sites/default/sqlconf.php  6      0
----------------------------------------------------------------------
A TOTAL OF 6 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 1 mins, 56.52 secs; Memory: 505.01MB
```

This is kind of funny actually, because it means we get to fix the sqlconf.php that is created during setup.php to make that go away:
https://github.com/openemr/openemr/blob/master/library/classes/Installer.class.php#L440-L476

:)

**Comment by prondubuisi** [comment]
Looks good @bradymiller 

> ok, the docker is now updated and live :)
> Here is the command to create a report of PSR2 issues:
> 
> ```
> docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cd openemr; php -d memory_limit=512M /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcs -n --extensions=php,inc --standard=ci/phpcs.xml --report=full .'
> ```
> 
> And here is the command to fix the PSR2 issues:
> 
> ```
> docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cd openemr; php -d memory_limit=512M /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcbf -n --extensions=php,inc --standard=ci/phpcs.xml .'
> ```
> 
> Interestingly, here is the output I get now with both commands:
> 
> ```
> [00:54][brady2@brady2-gaz:/var/www/openemr]$ docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cd openemr; php -d memory_limit=512M /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcs -n --extensions=php,inc --standard=ci/phpcs.xml --report=full .'
> 
> FILE: /var/www/localhost/htdocs/openemr/sites/default/sqlconf.php
> ----------------------------------------------------------------------
> FOUND 6 ERRORS AFFECTING 6 LINES
> ----------------------------------------------------------------------
>   5 | ERROR | [x] Spaces must be used for alignment; tabs are not
>     |       |     allowed
>   6 | ERROR | [x] Spaces must be used for alignment; tabs are not
>     |       |     allowed
>   7 | ERROR | [x] Spaces must be used for alignment; tabs are not
>     |       |     allowed
>   8 | ERROR | [x] Spaces must be used for alignment; tabs are not
>     |       |     allowed
>   9 | ERROR | [x] Spaces must be used for alignment; tabs are not
>     |       |     allowed
>  31 | ERROR | [x] A closing tag is not permitted at the end of a PHP
>     |       |     file
> ----------------------------------------------------------------------
> PHPCBF CAN FIX THE 6 MARKED SNIFF VIOLATIONS AUTOMATICALLY
> ----------------------------------------------------------------------
> 
> Time: 1 mins, 52.06 secs; Memory: 505.01MB
> 
> [00:58][brady2@brady2-gaz:/var/www/openemr]$ docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cd openemr; php -d memory_limit=512M /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcbf -n --extensions=php,inc --standard=ci/phpcs.xml .'
> 
> PHPCBF RESULT SUMMARY
> ----------------------------------------------------------------------
> FILE                                                  FIXED  REMAINING
> ----------------------------------------------------------------------
> ...ocalhost/htdocs/openemr/sites/default/sqlconf.php  6      0
> ----------------------------------------------------------------------
> A TOTAL OF 6 ERRORS WERE FIXED IN 1 FILE
> ----------------------------------------------------------------------
> 
> Time: 1 mins, 56.52 secs; Memory: 505.01MB
> ```
> 
> This is kind of funny actually, because it means we get to fix the sqlconf.php that is created during installation to make that go away:
> https://github.com/openemr/openemr/blob/master/library/classes/Installer.class.php#L440-L476
> 
> :)

Thanks for this @bradymiller . Devops is always full of surprises, lol.

**Comment by bradymiller** [comment]
all that is left to support is e2e since that requires some sort of headless chrome browser it appears

**Comment by bradymiller** [comment]
e2e is now supported :)
so closing this issue
