### ISSUE TITLE
Add Alias for PHP error log on docker 

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr-devops#234]
### Describe the Problem
In line with our aliasing other dev tools commands, I think it will be okay to also alias the PHP error log command for consistency. Also a close comparison of the command and proposed alias show that the alias is a bit shorter and easier to commit to memory 

    docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cat /var/log/apache2/error.log'

    ```
    docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c '/root/devtools php-log'

### Describe Solution
  add php error log alias
    docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c '/root/devtools php-log'

**Comment by bradymiller** [comment]
hi @prondubuisi ,
I like it.
Could shoot for the next docker to have the api setting support and this log command.
Hopefully I will also be able to fix this annoying docker bug that is showing up in some deployments by then also: https://github.com/openemr/openemr/issues/3297

**Comment by prondubuisi** [comment]
Cool @bradymiller Will keep an eye  on all of these. thanks
