### ISSUE TITLE
Turn on API from docker environment

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr-devops#235]
Hello @bradymiller you mentioned there is need to turn on the API from docker, Would be happy to work on this if I get the context for this feature and some pointers, thanks
https://community.open-emr.org/t/openemr-flex-docker-updated/12051/39

**Comment by bradymiller** [comment]
hi @prondubuisi ,
Regarding the API turn on, basically mean to turn it on by default (the API is turned off by default in Administration->Globals->Connectors->Enable OpenEMR REST API)

You can see examples of how did this in travis:
https://github.com/openemr/openemr/blob/master/.travis.yml#L129
(ignore the docker stuff in this line)

The goal would be to have a docker environment setting where can turn the api on by default

**Comment by prondubuisi** [comment]
Hello @bradymiller, any Need for an environment variable here https://github.com/openemr/openemr/blob/master/docker-compose.yml#L48, like TURN_API_ON : "yes"

**Comment by bradymiller** [comment]
yes. And that environment variable looks good
