### ISSUE TITLE
Allow PATCH Method in docker OpenEMR.conf

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr-devops#238]
### Describe the Problem
OpenEMR dockers do not support the PATCH Method, while this was okay in the past, we now have PATCH related operations within OpenEMR FHIR, and it has become necessary to add support for PATCH

### Describe Solution
As @bradymiller mentioned this can be fixed by adding the PATCH method here
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-3.10/openemr.conf#L25 on relevant dockers

**Comment by bradymiller** [comment]
Perfect timing, since I was about to push this PR. I'll take this one :)
