### ISSUE TITLE
Issues :(

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr-devops#24]
Tested twice and I'm getting "ERR_CONNECTION_REFUSED"

Launch script runs to the end but when logged in as root docker ps doesn't show any running containers.

**Comment by MatthewVita** [comment]
@TheToolbox @jesdynf

**Comment by MatthewVita** [comment]
Also, Travis is upset: https://travis-ci.org/openemr/openemr-devops/builds/284853380?utm_source=email&utm_medium=notification

**Comment by jesdynf** [comment]
Send me /tmp/lightsail-launch.log .

**Comment by MatthewVita** [comment]
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/bina
ry-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones us
ed instead.

**Comment by MatthewVita** [comment]
oops

**Comment by TheToolbox** [comment]
I'm away from a machine to replicate the build issues on but it looks either transient or like something changed in one of the apt repositories. I'll tell Travis to try again.

**Comment by TheToolbox** [comment]
Oh that's the same issue. Looks like someone removed a package?

**Comment by MatthewVita** [comment]
This is super weird to me

**Comment by MatthewVita** [comment]
It's using official apt sources, right???

**Comment by jesdynf** [comment]
Yup. This kind of thing Just Happens -- earlier in the cycle I saw the same thing, irreplicable Travis build errors due to transient network issues.

**Comment by TheToolbox** [comment]
It happened again on another Travis run

**Comment by jesdynf** [comment]
Yeah, if you look at the build history it failed, passed, and failed again.

**Comment by jesdynf** [comment]
Checking StackOverflow suggests that it's a misbehaving CDN, or at least that's what it usually is when this happens.

**Comment by jesdynf** [comment]
The build just passed.

**Comment by TheToolbox** [comment]
Travis succeeded again finally.ill go ahead and close it as transient!
