### ISSUE TITLE
Docs Issue: README.md link broken.

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr-devops#241]
In docker > openemr > All OpenEMR version folder 
e.g. https://github.com/openemr/openemr-devops/tree/master/docker/openemr/5.0.3
Some link was broken, and it can upgrade to https.

Please assign this issue to me, Thanks.

**Comment by bradymiller** [comment]
hi @stu01509 , it is yours :)

**Comment by stu01509** [comment]
Hi @bradymiller sir

Now, we can close this issue :)
