### ISSUE TITLE
Expand dev tools in the development flex dockers

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#243]
See this issue for details:
https://github.com/openemr/openemr/issues/3327

**Comment by prondubuisi** [comment]
Hello @bradymiller I have looked into Step 2 from openemr/openemr#3327

> 2. Then we can do a command that does a `empty-openemr`, which then drops the openemr database, and restores an empty `sites/default/` from `/openemr/sites/default`. What this setting will do is basically clear the current install of OpenEMR, which means the dev will get to go through the manual install process (via setup.php), thus making development in installation scripts super easy.

I am wondering why we need to empty the  entire `sites/default` directory as I just compared its contents [here](https://github.com/openemr/openemr/tree/master/sites/default) and it looks exactly like what I have locally

**Comment by bradymiller** [comment]
Note we are not emptying the sites/default directory. We are just resetting it back to its original form within the docker.

**Comment by prondubuisi** [comment]
Sounds more like it @bradymiller . Would love to take this up. I think I need another OpenEMR install. Can't affford to drop my tables or touch sites/default in my current install, How can one restore sites/default to its default state using ssh?

**Comment by bradymiller** [comment]
hi @prondubuisi ,

The key to this is the following shared volume:
https://github.com/openemr/openemr/blob/master/docker-compose.yml#L30
This is done in a way that he code in /openemr/sites/default in the docker does not get modified even when changes happen at /var/www/localhost/htdocs/openemr/sites/default in the docker.

Thus if :
1. Empty /var/www/localhost/htdocs/openemr/sites/default
2. Copy from /openemr/sites/default to /var/www/localhost/htdocs/openemr/sites/default
(this will essentially reset /var/www/localhost/htdocs/openemr/sites/default to defaults settings)

Then can drop the database.

Then at this point the developer can do a manual install via the setup.php script.

**Comment by tywrenn** [comment]
Bump

**Comment by bradymiller** [comment]
Thinking of following devtool commands:
- reset (resets OpenEMR as discussed above )
- reset-install (resets OpenEMR and then does an autoinstall)
- reset-install-demodata (resets OpenEMR and then does an autoinstall with same demo data that is used in demo farm)

**Comment by prondubuisi** [comment]
Following to see  how this comes to life @bradymiller

**Comment by bradymiller** [comment]
hi @prondubuisi , Just brought in the changes and updated the dockers:
https://github.com/openemr/openemr-devops/commit/ac83e541d359249a89bbd3122c131a0dc2458ae3
https://github.com/openemr/openemr/commit/4d6a4925198e16aeb7c6b1b4d45ab4c4068efefc

As a bonus, also added support for multisite :)

**Comment by bradymiller** [comment]
https://community.open-emr.org/t/openemr-flex-docker-updated/12051/59
