### ISSUE TITLE
Fix PHP Codesniffer

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr-devops#257]
For fixing PSR12 issues, we should be running this command instead of the one in the current script:
`phpcbf -p -n --extensions=php,inc --report-width=120 --standard=ci/phpcs.xml --report=full .`

**Comment by jesdynf** [comment]
Hi, Tyler.

Where in the current script do we run that?

**Comment by bradymiller** [comment]
we currently use for

fix:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-3.12/utilities/devtools#L38

report:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-3.12/utilities/devtools#L19

**Comment by bradymiller** [comment]
Looks like you want the following parameter added, correct? :
```
-p
--report-width=120
```
if so, happy to add this for the next flex docker builds

**Comment by bradymiller** [comment]
Should we also ensure these parameters are in the report (phpcs command) ?

**Comment by tywrenn** [comment]
Yes we should add these in both (i haven't tested the other cmd yet it should be there too). The reason that this is needed is to mirror what Travis would usually display. It also gives a progress indicator instead of not showing one at all which is very helpful.

**Comment by bradymiller** [comment]
done :) (included it in following commit and updated dockers)
https://github.com/openemr/openemr-devops/commit/5e1c5990ed67b3c63ca2e955715e4a3d2736e438
