### ISSUE TITLE
Import foreign certificate to Docker after install

### ISSUE THREAD

**Issue by jesdynf** [openemr/openemr-devops#27]
If a user supplies SSL certificates, we should support a clean way to import them.

**Comment by TheToolbox** [comment]
The easiest way to do this is likely to start up the image with the host filesystem mounted into the container at the appropriate directory. That being said, this would require specific file naming or a symlink in the host fs.

**Comment by TheToolbox** [comment]
You could also do it as a one-time thing with some form of `sudo docker cp /dir/cert container:/etc/ssl/certs/self-signed.cert.pem`
