### ISSUE TITLE
flex-3.12 - failed.

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr-devops#276]
docker build with:
EASY_DEV_MODE=yes
EASY_DEV_MODE_NEW=yes

Error - 
```
Running quick setup!

OpenEMR configured.
Setup Complete!
rsync: link_stat "/couchdb/data" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1189) [sender=3.1.3]
```
Command found in - docker/openemr/flex-3.12/autoconfig.sh:309

**Comment by bradymiller** [comment]
hi @matrix-amiel ,
What does your full docker-compose.yml look like?
Are you using most recent flex-3.12 docker?
Are you using most recent codebase?

**Comment by matrix-amiel** [comment]
hi @bradymiller 
We have our image base from Openemr images, Yes yesterday I began to upgrade our environments and I updated to the most last version of Openemr and devops.

We run docker with standard commands, we haven't docker-compose and we do not use CouchDB.
```
docker run \
        --name $INSTALLATION_NAME \
        -p $OPENEMR_PORT:80 \
        --env EASY_DEV_MODE=yes \
        --env EASY_DEV_MODE_NEW=yes \
        --env FORCE_NO_BUILD_MODE=yes \
        --env MYSQL_HOST=$MYSQL_HOST \
        --env MYSQL_DATABASE=$INSTALLATION_NAME \
        --env MYSQL_USER=$INSTALLATION_NAME \ 
        --env-file $CLINIKAL_DEVOPS_PATH/creds.cfg \ # root user names and password
        -v $FULL_HOST_CODEBASE_PATH/openemr:/openemr:ro \
        -v $FULL_HOST_CODEBASE_PATH/openemr:/var/www/localhost/htdocs/openemr \
        israelimoh-image
```
In flex 3.11 it works well...
seems the file '/couchdb/data' not found, maybe prefer to check if exists before the command.
