### ISSUE TITLE
Installation script fails for MacOS BigSur

### ISSUE THREAD

**Issue by sahasrarjn** [openemr/openemr-devops#278]
### Installation script fails for MacOS BigSur

The installation script stops execution with the message "The script only supports macOS10.13 and later."

### To Reproduce
Standard env installation using scripts.
`./openemr-env-installer` on MacOS (BigSur)

**Comment by bradymiller** [comment]
hi @sahasrarjn , I'm not very knowledgeable on the mac side of things, but @reidliu41 may have some input. It does appear that BigSur was recently released (after the building of the script). Guessing you could build out else blocks for BigSur where it is done for Darwin and see if it works (doing the same stuff that is done in Darwin code blocks); would be a good improvement to the script so it will work for new MacOs.

**Comment by sahasrarjn** [comment]
Sure I'll try to fix the script. Can you assign this issue to me?

**Comment by bradymiller** [comment]
just did some research and realized that darwin includes all MacOs versions and may it will just involve a fix to how the version is collected here:
https://github.com/openemr/openemr-devops/blob/master/utilities/openemr-env-installer/openemr-env-installer#L494-L501

**Comment by bradymiller** [comment]
issue is yours :)

**Comment by reidliu41** [comment]
@bradymiller @sahasrarjn thanks
