### ISSUE TITLE
Kubernetes kub-up and .yaml files only expose Cluster-IP address for openemr pod

### ISSUE THREAD

**Issue by TheCranston** [openemr/openemr-devops#289]
### Describe the problem

When running on a rancher based kubernetes cluster, the included yaml files in openemr-devops/kubernetes/minikube do not expose the web interface to the local IP subnet or utilize a load balancer for services.  There are issues with replicas beyond 1 with persistent volume claims trying to be shared by which they fail.

### Describe the solution you'd like

I'd really like a helm chart for the installation.  But short of that a set of yaml files that will expose the openEMR web interface via a load balancer like metalLB to an externalIP address, rather than a Cluster-IP which is typically not reachable.  I'd even settle for an ingress nginx method.  Also, address the PV setup so that replicas can be scaled beyond 1.  I'm a totally new to this and my hacking at the scripts have not been successful.  thanks in advance.

**Comment by jesdynf** [comment]
Hello,

I'd recommend making this request on the forums. I'm sure you're correct about the problem you're describing, but I'm not aware we have the expertise to provide what you're asking for.
