### ISSUE TITLE
QA Day II Issues :)

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr-devops#29]
Hello everybody, 

I have tested the OpenEMR Lightsail solution again today and was able to accomplish the following: 

1. Logging in 
2. Changing the password 
3. Creating patients
4. Creating a patient encounter to upload blood pressure vitals of 120 over 80 
5. Uploading a patient document 
6. Rebooting the system 
7. Changing some of the administrative settings 
8. General smoke testing with the user interface 

Unfortunately, I actually ran into a few things: 

- "Need access to the containers? Log into root (sudo -i), and..." section commands didn't work for me. I had to use the good old docker ps, manually find the hash, enter in docker exec -it hash /bin/sh 

- Backup cron didn't work: 

bsdmainutils  logrotate          mlocate  update-notifier-common
root@ip-172-26-13-213:/etc/cron.daily# cat duplicity-backups 
#!/bin/bash

docker exec $(docker ps | grep mysql | cut -f 1 -d " ") /root/xbackup-wrappe
r.sh
duplicity --no-encryption --full-if-older-than 9D --include $(docker volume 
inspect docker_sqlbackup | jq -r ".[0].Mountpoint") --include $(docker volum
e inspect docker_sitevolume | jq -r ".[0].Mountpoint") --exclude '**' / file
:///root/backups/
duplicity remove-all-but-n-full 2 --force file:///root/backups/
root@ip-172-26-13-213:/etc/cron.daily# ./duplicity-backups 
Error: No such volume: docker_sqlbackup
Error: No such volume: docker_sitevolume
Fatal Error: The file specification
    null
cannot match any files in the base directory
    /
Useful file specifications begin with the base directory or some
pattern (such as '**') which matches the base directory.
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: none
No old backup sets found, nothing deleted.

**Comment by jesdynf** [comment]
Is this Lightsail instance still up? I can log in tonight and review it.

**Comment by jesdynf** [comment]
If this comes up again, please get me copies of the docker process and volume lists"

**Comment by jesdynf** [comment]
Not gonna lie, I don't get what happened, but all the container and volumes changes from being named docker_ to singleserver_. Might be the site repo reorg doing... something to the context I don't get.

**Comment by MatthewVita** [comment]
lol!

Thanks,

Matthew Vita
www.matthewvita.com
