### ISSUE TITLE
Login Credentials

### ISSUE THREAD

**Issue by PoovizhiKannan-PK** [openemr/openemr-devops#294]
### Describe the bug

What are the Login credentials for OpenEMR. I launched it via AWS - OpenEMR Cloud - Standard Edition

**Comment by jesdynf** [comment]
When you launch Standard you configure details like the administrator (user: `admin`) and database passwords during CloudFormation launch.

**Comment by PoovizhiKannan-PK** [comment]
Can you please provide me with documentation on how to configure it?
