### ISSUE TITLE
AMI Not Found

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr-devops#30]
<img width="1626" alt="screen shot 2017-10-08 at 4 02 38 pm" src="https://user-images.githubusercontent.com/1715206/31320415-323a3536-ac42-11e7-9025-5ab5989750df.png">

**Comment by jesdynf** [comment]
It's only in us-east–1, yes. Actual marketplace deployment is different.

**Comment by MatthewVita** [comment]
Okay, not sure why they put me in IRELAND LOL

**Comment by MatthewVita** [comment]
> Launch Failed
Volume of size 10GB is smaller than snapshot 'snap-005f73a322299153e', expect size >= 50GB

This was the only hiccup. Not a big deal... we'll just have the user choose at least 50

**Comment by jesdynf** [comment]
I set it to 50 because I thoufht it was the minimum safe size to accept patient documents. I didn't know partiton resizing was on the table; next instance will be 10gig and I'll see how upsizing works.
