### ISSUE TITLE
Composer binary needs to be upgraded

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr-devops#305]
Installed composer version is 2.0.8 but when trying to use a Github token there is a failure. Issue is fixed with composer 2.1.14

See [this tweet](https://twitter.com/seldaek/status/1395375090603286534) by the developer of Composer regarding the problem

Running `apk upgrade composer` did not bring down an update, I had to manually upgrade via the traditional composer install scripts at getcomposer.org

**Comment by bradymiller** [comment]
Just updated the `flex` docker to alpine 3.15. Since most recent composer is installed when do a docker build, this issue should go away:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-3.15-8/Dockerfile#L23
