### ISSUE TITLE
Open EMR AWS Standard Cloud Formation 

### ISSUE THREAD

**Issue by andrewbertran** [openemr/openemr-devops#308]
I tried installing the Open EMR AWS Standard Cloud Formation from the AWS marketplace but keep getting the stack error that the WebServerInstance failed. The EC2 instance is created and running but I'm unable to SSH using the designated keyfile (added port 22 to the security group) or access it through the browser. 

![image](https://user-images.githubusercontent.com/87007750/145471428-36eff2bc-73a3-457e-9740-8c64f8d50065.png)
![image](https://user-images.githubusercontent.com/87007750/145471702-11302cd2-bb42-4b63-b5c6-7dcda6fc0482.png)

There are no Outputs in the output tab which I believe is supposed to show my instances public IP.
All other components (DB in RDS, VPC, S3 etc.. get created successfully)

I left the Subnet and VPC settings at their default values. 
The marketplace states OpenEMR version: 6.0.0 (Mar 10, 2021).
I also tried updating the Cloud formation template to use MySQL 5.7.

Does anyone have a more up to date Cloud formation template that works?

Thanks,
Andrew

**Comment by andrewbertran** [comment]
Update, I was able to connect to the server as ubuntu user and access root. 
After navigating to /root/openemr-devops/packages/standard/ I ran docker-compose up and got an error that the docker-compose.yml was using an incompatible version. I switched the version to 2.0 and then ran it again. Now the docker container is running and accessible through the browser. Im guessing it initially installed an older version of docker-compose.

To replicate the error after creating the stack.
SSH into the EC2 instance
Sudo -i
cd /root/openemr-devops/packages/standard/
docker-compose up

**Comment by jesdynf** [comment]
Great job identifying that -- thanks! I have no idea what's going on in there but that's enough to get me looking (without the tests I couldn't run until this weekend).

By any chance do you know what version the file was showing before you fixed it?

**Comment by stephenwaite** [comment]
was working on a `standard` yesterday
```
docker-compose version 1.15.0, build e12f3b9
```

**Comment by jesdynf** [comment]
Sorry, what internal version the `docker-compose.yml` was reporting, because I cannot recall changing that recently and it should be pretty static.

**Comment by stephenwaite** [comment]
`docker-compose.yaml` in `standard` directory is `3.1`

**Comment by jesdynf** [comment]
And that /works/ on the Standard you've installed? I knew I hadn't changed it recently.

**Comment by stephenwaite** [comment]
yes, just did a `docker-compose up` yesterday for let's encrypt

**Comment by stephenwaite** [comment]
maybe @andrewbertran didn't run `./docker-compose up` and instead grabbed the ubuntu version

**Comment by ralflukner** [comment]
@stephenwaite 
I'm having the same problem on AWS when attempting to create STANDARD.
Is there a new cloudformation template file that works?  How do I work around this problem?

**Comment by jesdynf** [comment]
This got fixed in the https://community.open-emr.org/t/openemr-6-1-0-devops/18069 push.
