### ISSUE TITLE
Support capsule/snapshots from demo farm to the easy/insane dev docker devtools

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#317]
1. Allow dash in name when doing backup/restore of capsule/snapshot (docker dev environment) (DONE)
2. In the restore, only do the couchdb thing if a data folder actually exists in the capsule/snapshot (docker dev environment) (DONE)
3. Empty the database before the restore in both the docker dev environment and the demo environment; can basically do same line as in done demo data code in the dev docker and demo farm** (dev docker DONE; demo farm DONE)
4. The onsite_activity_view view is breaking restore when backup database and then restore with another database name since mysqldump of views included the database name, thus either will break on import or even worse will do a view with another database on the server (think multisite) if it happens to have the same database name as the mysqldump script:
  - link describing issue: https://jira.mariadb.org/browse/MDEV-22282
  - example of what a mysqldump looks like for view (note the `edu` database name is hardcoded):
```
/*!50001 VIEW `onsite_activity_view` AS select `edu`.`onsite_portal_activity`.`status` AS `status`,`edu`.`onsite_portal_activity`.`narrative` AS `narrative`,`edu`.`onsite_portal_activity`.`table_action` AS `table_action`,`edu`.`onsite_portal_activity`.`table_args` AS `table_args`,`edu`.`onsite_portal_activity`.`action_user` AS `action_user`,`edu`.`onsite_portal_activity`.`action_taken_time` AS `action_taken_time`,`edu`.`onsite_portal_activity`.`checksum` AS `checksum`,`edu`.`patient_data`.`title` AS `title`,`edu`.`patient_data`.`fname` AS `fname`,`edu`.`patient_data`.`lname` AS `lname`,`edu`.`patient_data`.`mname` AS `mname`,`edu`.`patient_data`.`DOB` AS `DOB`,`edu`.`patient_data`.`ss` AS `ss`,`edu`.`patient_data`.`street` AS `street`,`edu`.`patient_data`.`postal_code` AS `postal_code`,`edu`.`patient_data`.`city` AS `city`,`edu`.`patient_data`.`state` AS `state`,`edu`.`patient_data`.`referrerID` AS `referrerID`,`edu`.`patient_data`.`providerID` AS `providerID`,`edu`.`patient_data`.`ref_providerID` AS `ref_providerID`,`edu`.`patient_data`.`pubpid` AS `pubpid`,`edu`.`patient_data`.`care_team_provider` AS `care_team_provider`,`edu`.`users`.`username` AS `username`,`edu`.`users`.`authorized` AS `authorized`,`edu`.`users`.`fname` AS `ufname`,`edu`.`users`.`mname` AS `umname`,`edu`.`users`.`lname` AS `ulname`,`edu`.`users`.`facility` AS `facility`,`edu`.`users`.`active` AS `active`,`edu`.`users`.`title` AS `utitle`,`edu`.`users`.`physician_type` AS `physician_type`,`edu`.`onsite_portal_activity`.`date` AS `date`,`edu`.`onsite_portal_activity`.`require_audit` AS `require_audit`,`edu`.`onsite_portal_activity`.`pending_action` AS `pending_action`,`edu`.`onsite_portal_activity`.`action_taken` AS `action_taken`,`edu`.`onsite_portal_activity`.`id` AS `id`,`edu`.`onsite_portal_activity`.`activity` AS `activity`,`edu`.`onsite_portal_activity`.`patient_id` AS `patient_id` from ((`onsite_portal_activity` left join `patient_data` on(`edu`.`onsite_portal_activity`.`patient_id` = `edu`.`patient_data`.`pid`)) left join `users` on(`edu`.`patient_data`.`providerID` = `edu`.`users`.`id`)) */;
```
  - fixed by ignoring the view in the mysqldump (DONE)
6. sql conf needs adjusting (follow same strategy as demo farm, after the standard install copy sqlconf.php somewhere, then bring in snapshot drive, then bring in original sqlconf.php) (DONE)
```
modify the sqlconf.php file.  (prior settings commented out)
/*
$host   = 'mysql-openemr';
$port   = '3306';
$login  = 'edu';
$pass   = 'edu';
$dbase  = 'edu';
*/
$host   = 'mysql';
$port   = '3306';
$login  = 'openemr';
$pass   = 'openemr';
$dbase  = 'openemr';
```

7. Fix everything that is wrong with OpenEMR and the world (this could take awhile :) )

**Comment by adunsulag** [comment]
@bradymiller I just pulled the latest easy-dev docker and the restore still fails if the CouchDB data folder doesn't exist.  Not sure if you want to re-open this or open a new issue.
