### ISSUE TITLE
easy dev compose up loses themes

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr-devops#320]
### Describe the bug

write concise description of what the bug is.
after running
```
docker-compose up -d
```
from the `docker/easy-development`directory there are no themes to be found
prob related to the [rework of the ccda service](https://github.com/openemr/openemr/pull/5319/files) combined with how `public/assets` are removed

### To Reproduce
![Screenshot from 2022-05-14 17-27-04](https://user-images.githubusercontent.com/5618372/168448693-4d07fa5d-7823-461d-85c4-88caf141f715.png)

**Comment by stephenwaite** [comment]
for now can just get into the docker openemr directory and run npm install and then 
```
docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c '/root/devtools build-themes'
```
to rebuild them

**Comment by jesdynf** [comment]
We could integrate that command into the container start but I don't know when to /use/ it. By any chance can you give me a shell command that would /detect/ such a broken theme? Is the theme missing because a specific file hasn't been compiled or copied to the right location, and we could detect that missing file and run the theme fixer?

**Comment by bradymiller** [comment]
It worked for me this morning on a new build (tear down with openemr-cmd
down and then openemr-cmd up) although i do not work/build in same
directory as my repo. Will try it again later tonight from master to make
sure it works.

**Comment by bradymiller** [comment]
Confirmed that easy dev worked in my environment with most recent master. Would make sure the shared volumes have been removed since this can break the dev docker builds.
