### ISSUE TITLE
there are 2 separate php error logs

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr-devops#325]
There is now 2 separate php error logs (one for without ssl and one for when using ssl), which makes it more difficult for users to troubleshoot. Is this needed:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/7.0.1/openemr.conf#L68-L69
(ie. if remove these 2 lines, will the ssl error/access logs then go to the logs defined above that?)

**Comment by bradymiller** [comment]
Just seems like it adds another layer of potential confusion for users/troubleshooting. For example, user has issues, we say look at php logs, they ask where, we say either in this place or that place depending on if using http (behind lb for example) or https. If ok with it, I may just try to remove the 2 lines to see what happens (the virtualhost at 80 goes to the log at top so assuming the one at 443 will also).

**Comment by bradymiller** [comment]
btw, if works, will only do for 7.0.1/flex dockers (will leave 7.0.0 as is since could get more confusing depending on which 7.0.0 docker they are using.

**Comment by jesdynf** [comment]
I mean, yeah, try it on `next` and then just see what it does, if they both hit the same place that's great, just as long as 80 and 443 both positively leave notes in the same place.
