### ISSUE TITLE
(development-easy/flex) Docker for Windows Takes Forever to Generate SSL Key File

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr-devops#327]
### Describe the bug

Running Docker on Windows on the development-easy/flex branch takes a long time to load and seems to be getting stuck on generating SSL key files in the beginning. I recommend finding ways to optimize this in Docker, maybe move the SSL generation later during the launch sequence?

### Client configuration

- OpenEMR version: Running on master branch on OpenEMR Github
- Operating system: Windows 11 64-bit with 8GB of RAM

**Comment by jesdynf** [comment]
There's not a lot that could be usefully done here -- it has to happen and the idea of embedding even a development, not-for-production server with default certs and key makes me itch.

However, you could probably stop having to do it after the first time if you wanted. Review https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-3.15-8/ssl.sh and notice that it's running the OpenSSH call every launch if it can't find a key it's made? Extract the keys it makes (`/etc/ssl/private/selfsigned.key.pem`, `/etc/ssl/certs/selfsigned.cert.pem`) from your container, put them on the host somewhere, and then extend your personal docker-compose file to add those single files from your host as Docker volumes ( https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume ) and then the container boot won't make the expensive call on subsequent launches.

Sound workable?
