### ISSUE TITLE
NFS support

### ISSUE THREAD

**Issue by jesdynf** [openemr/openemr-devops#33]
Not all Amazon regions have EFS support. Support NFS as an option, even if that means high-availability (multi-AZ) isn't feasible.

**Comment by MatthewVita** [comment]
Interesting! So this would be more of a traditional NFS approach right?

**Comment by jesdynf** [comment]
Yes. The document store would still apply as it has, and it would be more
expensive than the regular version because the server would be more
expensive until some crossover point I haven't mapped out, and NFS isn't as
good as EFS in this role, but it would suffice to spread coverage to more
regions.

If there was a user in (say) Frankfurt who wanted this local and didn't
need dual-AZ, this would be for him.
