### ISSUE TITLE
development-easy-light docker failed to start due to /couchdb/data

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr-devops#350]
![Screenshot from 2023-01-31 17-10-03](https://user-images.githubusercontent.com/5618372/215895237-1260a62b-9695-4567-bb73-9c11076fcc1b.png)

**Comment by bradymiller** [comment]
may be best to just drop light unless there is a good argument to keep it.

**Comment by stephenwaite** [comment]
guess this belonged in `openemr` repo then so will close issue
