### ISSUE TITLE
Add Opcache to docker images.

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr-devops#356]
Add the ability to have the opcache setup for the docker environments the same way we do xdebug.  If the xdebug is enabled we want to disable the JIT compiler since they can't run at the same time.  The opcache with testing against the APIs was improving performance by 50% and the JIT improves performance by another 50%, IE 75% speed gains were seen in the APIs by enabling the opcache module and configuring it with JIT.

We want to be able to enable this by default for the docker images as long as it doesn't break existing functionality.

**Comment by adunsulag** [comment]
@jesdynf It's a language caching layer that caches a lot of the PHP syntax tree, function, and class codes that are abstracted from the PHP class.  It also has a just in time compiler that improves performance even more. Its usually turned on by default for production php installations and I thought we had it turned on but we don't. 

When you enable it in php it operates seamlessly and you don't have to trigger it via code normally as the php extension will monitor the cache and purge it as needed based on the ini settings.

When its turned on you'll see something like this in the phpinfo page <?php phpinfo(); ?>. (This screenshot has JIT disabled).
![image](https://github.com/openemr/openemr-devops/assets/228117/f7320bcb-4511-463d-8311-ce1691b15974)

**Comment by jesdynf** [comment]
parallel PR approved in lieu
