### ISSUE TITLE
bug: Lightsail setup fails on Ubuntu 20.04 with openssh-server package update

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr-devops#370]
I'm following the lightsail guide here: https://github.com/openemr/openemr-devops/tree/master/packages/lightsail

Unfortunately, its failing to setup the instance and just sits there on the openssh-server configuration:
Output from ps aux
```
root       20935  0.0  2.0  26868 19576 pts/0    S+   21:56   0:00 /usr/bin/perl -w /usr/share/debconf/frontend /var/lib/dpkg/info/openssh-server.postinst configure 1:8.2p1
root       20947  0.0  0.1   2608  1752 pts/0    S+   21:56   0:00 /bin/sh /var/lib/dpkg/info/openssh-server.postinst configure 1:8.2p1-4ubuntu0.1
root       20952  0.0  0.3   8880  3488 pts/0    S+   21:56   0:00 /bin/bash /usr/bin/ucf --three-way --debconf-ok --sum-file /usr/share/openssh/sshd_config.md5sum /tmp/fil
root       20999  0.0  0.4  12052  4068 pts/0    S+   21:56   0:00 whiptail --backtitle Package configuration --title Configuring openssh-server --output-fd 11 --nocancel -
```
I looked at the lightsail-launch.log file and it looks like its stuck on an upgrade config choice.  I've attached the log for the launch.
[lightsail-launch.log](https://github.com/openemr/openemr-devops/files/12666867/lightsail-launch.log)

```

  ┌──────────────────────┤ Configuring openssh-server ├──────────────────────┐
  │ A new version (/tmp/filemfYLP9) o
f │ /etc/ssh/sshd_config is available, but the version installed currently   │
  │ has been locally modified.                                               │
  │                                                                          │
  │ What do yo
u │ant to do about modified configuration file sshd_config?    │             │
  │           install the package maintainer's version                       │
  │           keep the local version c
  │
sh│w a 3-way ddo a 3-way merge between available versions      │             │
  │           start a new shell to examine the situation                     │
  │                                                                          │
  │                                                                          │
  │                                  <Ok>                                    │
  │                                                                          │
  └──────────────────────────────────────────────────────────────────────────┘
```

If I'm doing something wrong, happy to be pointed in the right direction

**Comment by adunsulag** [comment]
@jesdynf Any thoughts on if this is a recent change, or something I'm doing wrong here?

**Comment by jesdynf** [comment]
Shouldn't be anything you're doing. Looks like the version of Ubuntu you're using saw some sort of post-setup configuration or hardening (turning off RSA I bet) and the update script doesn't know how to handle it.

Try downloading the launch.sh file and adding an early `export DEBIAN_FRONTEND=noninteractive` to it (see https://unix.stackexchange.com/questions/22820/how-to-make-apt-get-accept-new-config-files-in-an-unattended-install-of-debian-f) and I'll look at trying to help tonight.

**Comment by adunsulag** [comment]
I won't be able to try it out until tomorrow morning but it looks like that would fix it if we can put it in noninteractive mode.  I'll give it a try and let you know. Thanks for the very fast response!
