### ISSUE TITLE
Attempting to install on openemr-cmd on macOS and it is not working. 

### ISSUE THREAD

**Issue by toduyemi** [openemr/openemr-devops#376]
I'm attempting to install openemr-cmd following the instructions on the readMe with the scripts provided? When i try to run the "openemr-cmd" i receive a "openemr-cmd: command not found". 

Is this tool not macOS compatible? 

How can I run a local dev environment of opener without it?

**Comment by jesdynf** [comment]
Sorry for the delay on this. It sounds like you might not have the utility in your path, or ~/bin might not be in your path.
