### ISSUE TITLE
Implement Changes to How JIT is Configured to Work With PHP v8.4

### ISSUE THREAD

**Issue by Jmevorach** [openemr/openemr-devops#386]
To be clear this is definitely not an issue yet especially since PHP v8.4 isn't even released yet! 

I wanted to open up an issue for this as soon as I learned about it so I didn't forget and we all were aware before we start doing anything with PHP 8.4.

In short right now `opcache.jit` defaults to `tracing`. Starting in PHP v8.4 it will default to `disabled`.

More information can be found [here](https://wiki.php.net/rfc/jit_config_defaults) .

So at some point before we do anything with PHP v8.4 (when it's available) we should insert a line [just below here in OpenEMR.sh](https://github.com/openemr/openemr-devops/blob/master/docker/openemr/7.0.3/openemr.sh#L428) that does `echo "opcache.jit=tracing" >> /etc/php84/php.ini`.

**Comment by bradymiller** [comment]
hi @Jmevorach ,
Thanks for ensuring the settings maintain compatibility with future PHP versions!
No better time than the present to fix this :) https://github.com/openemr/openemr-devops/pull/387

**Comment by bradymiller** [comment]
fyi, can run OpenEMR with PHP8.4-dev via the Insane Development Docker Environment :)
https://github.com/openemr/openemr/issues/7122

**Comment by Jmevorach** [comment]
No problem; happy to help 🙂

And thanks for putting in a PR for it! 

I’ll try to continue to keep an eye out for stuff like this!
