### ISSUE TITLE
bug: version 5.7.41 for mysql - OpenEMR Cloud Standard Edition - CloudFormation Issue

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr-devops#390]
### To Reproduce

1. Add a '....'

### Expected behavior

bug: https://community.open-emr.org/t/cannot-find-version-5-7-41-for-mysql-openemr-cloud-standard-edition-cloudformation-issue/22362

### Client configuration

- OpenEMR version:
- Operating system:

**Comment by Jmevorach** [comment]
Good afternoon @stephenwaite ! Hope this message finds you well.

I have proof that OpenEMR works for MySQL v8.0> 😊. 

See the line of code [here](https://github.com/openemr-transfer/host-openemr-on-aws-fargate/blob/main/openemr_ecs/openemr_ecs_stack.py#L255).

In the version of the CDK used (v2.133.0) the Aurora MySQL version referenced there is 8.03.6 which according to documentation [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.Versions.html) 

> [8.]3.x Aurora MySQL engine versions are wire-compatible with MySQL 8.0.23 onwards

This means that OpenEMR v7.0.2 is compatible with _at least_ MySQL v8.0.23. Hope this is helpful.

**Comment by Jmevorach** [comment]
Oh also @stephenwaite fun fact; that version of the Aurora MySQL engine (v3.06), according to documentation [here](https://aws.amazon.com/about-aws/whats-new/2024/03/aurora-mysql-integration-amazon-bedrock-generative-ai/):

> Today, AWS announces that [Amazon Aurora ML](https://aws.amazon.com/rds/aurora/machine-learning/) now provides access to foundation models available in Amazon Bedrock directly through SQL in the Aurora MySQL 3.06 version.

> Amazon Aurora ML exposes models as SQL functions, allowing you to use standard SQL to pass data to models and return model output as query results. It provides simple, optimized, and secure integration between Aurora and AWS machine learning services without having to build custom integrations or move data around. As an example, Aurora ML and Bedrock together can enable real-time summarization of customer support notes in Aurora to accelerate case resolution. Aurora ML can also pass current and relevant database information to Bedrock to improve chatbot responses.

This means we should in theory be able to write some modules in PHP that would allow OpenEMR installations running that version of the Aurora MySQL engine (which OpenEMR v7.0.2 supports) would allow for summarizing data in a way that was specific to a certain OpenEMR installation using something like [Claude 3](https://www.anthropic.com/news/claude-3-family) via [Bedrock](https://aws.amazon.com/bedrock/claude/).

**Comment by jesdynf** [comment]
I'll get this soon, but not today.

**Comment by jesdynf** [comment]
Prepping the revised CFT for AWS Marketplace now.
