### ISSUE TITLE
(Matthew) OpenEMR Smoketest

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr-devops#97]

**Comment by MatthewVita** [comment]
@bradymiller Looks like the https://github.com/openemr/openemr/blob/master/interface/forms/eye_mag/taskman.php is not happy on the eye form. Basically, I'm trying to export the report as a PDF and it's giving a 500. Should I get in touch with Ray or do you maybe know what's going on?

cc: @danielehrlich @jesdynf @johnbwilliams @andremillet (QA is going well otherwise... still have more smoke testing to do but I'm testing on a 2 day old OpenEMR Express instance, which is good)

**Comment by jesdynf** [comment]
What size instance?

**Comment by bradymiller** [comment]
hi @MatthewVita ,
Is this issue specific to the Cloud or can this also be duplicated on one of the 5.0.0 demos?
-brady

**Comment by bradymiller** [comment]
@MatthewVita and @ophthal  ,

Testing on main OpenEMR demo at http://www.open-emr.org/wiki/index.php/OpenEMR_Demo: 
When I tried to test in Eye Form, File->Save Report as PDF, nothing happens and the php error log shows:
``````
[17-Nov-2017 08:49:06 UTC] PHP Fatal error:  Uncaught <span style="color: #AA0000; font-weight: bold;">
ERROR nÂ°4</span><br>
File : /var/www/html/a/openemr/library/html2pdf/_class/parsingHtml.class.php<br>
Line : 118<br>
<br>
HTML code invalid, the tags are not closed in an orderly fashion.<br>Status : <pre>Array
(
    [0] => page
    [1] => div
    [2] => table
    [3] => tr
    [4] => td
)
</pre>
<br><br>HTML : ...Round and Reactive&lt;br /&gt;      &lt;/tr&gt;
    &lt;/table&gt;
        &lt;br /&gt;...
  thrown in /var/www/html/a/openemr/library/html2pdf/_class/parsingHtml.class.php on line 118
``````

**Comment by bradymiller** [comment]
btw, for above made an Issue on the OpenEMR repo here:
https://github.com/openemr/openemr/issues/1233

**Comment by ophthal** [comment]
I'll look into it this weekend...
